[build-system]
requires = ["hatchling", "pegen>=0.3.0"]
build-backend = "hatchling.build"

[project]
name = "Quantar"
dynamic = ["version"]
dependencies = [
    "numpy",
    "numba",
    "openqasm3[parser]",
]

[project.optional-dependencies]
backends = [
    "pennylane",
    "qiskit",
    "qbraid",
    "qiskit-aer",
]

[tool.hatch.version]
path = "__init__.py"

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build.targets.wheel]
packages = ["quantum", "stl", "lang_systems", "quantar"]
