[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Quantar"
dynamic = ["version"]
dependencies = [
    "numpy",
    "numba",
    "openqasm3[parser]",
]

[project.optional-dependencies]
backends = [
    "pennylane",
    "qiskit",
    "qbraid",
    "qiskit-aer",
]

[tool.hatch.version]
path = "__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["quantum", "stl"]
