#!/usr/bin/env python3.8
# @generated by pegen from lang_systems\quantar.gram

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser
# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Parser):

    @memoize
    def start(self) -> Optional[Any]:
        # start: file
        mark = self._mark()
        if (
            (file := self.file())
        ):
            return file;
        self._reset(mark)
        return None;

    @memoize
    def file(self) -> Optional[Any]:
        # file: statements $
        mark = self._mark()
        if (
            (statements := self.statements())
            and
            (_endmarker := self.expect('ENDMARKER'))
        ):
            return [statements, _endmarker];
        self._reset(mark)
        return None;

    @memoize
    def statements(self) -> Optional[Any]:
        # statements: statement+
        mark = self._mark()
        if (
            (_loop1_1 := self._loop1_1())
        ):
            return _loop1_1;
        self._reset(mark)
        return None;

    @memoize
    def statement(self) -> Optional[Any]:
        # statement: simple_stmt | compound_stmt
        mark = self._mark()
        if (
            (simple_stmt := self.simple_stmt())
        ):
            return simple_stmt;
        self._reset(mark)
        if (
            (compound_stmt := self.compound_stmt())
        ):
            return compound_stmt;
        self._reset(mark)
        return None;

    @memoize
    def simple_stmt(self) -> Optional[Any]:
        # simple_stmt: expr_stmt
        mark = self._mark()
        if (
            (expr_stmt := self.expr_stmt())
        ):
            return expr_stmt;
        self._reset(mark)
        return None;

    @memoize
    def expr_stmt(self) -> Optional[Any]:
        # expr_stmt: expr NEWLINE
        mark = self._mark()
        if (
            (expr := self.expr())
            and
            (_newline := self.expect('NEWLINE'))
        ):
            return [expr, _newline];
        self._reset(mark)
        return None;

    @memoize
    def compound_stmt(self) -> Optional[Any]:
        # compound_stmt: funcdef | if_stmt
        mark = self._mark()
        if (
            (funcdef := self.funcdef())
        ):
            return funcdef;
        self._reset(mark)
        if (
            (if_stmt := self.if_stmt())
        ):
            return if_stmt;
        self._reset(mark)
        return None;

    @memoize
    def funcdef(self) -> Optional[Any]:
        # funcdef: 'def' NAME '(' ')' ':' block
        mark = self._mark()
        if (
            (literal := self.expect('def'))
            and
            (name := self.name())
            and
            (literal_1 := self.expect('('))
            and
            (literal_2 := self.expect(')'))
            and
            (literal_3 := self.expect(':'))
            and
            (block := self.block())
        ):
            return [literal, name, literal_1, literal_2, literal_3, block];
        self._reset(mark)
        return None;

    @memoize
    def if_stmt(self) -> Optional[Any]:
        # if_stmt: 'if' expr ':' block (('elif' expr ':' block))* [('else' ':' block)]
        mark = self._mark()
        if (
            (literal := self.expect('if'))
            and
            (expr := self.expr())
            and
            (literal_1 := self.expect(':'))
            and
            (block := self.block())
            and
            (_loop0_2 := self._loop0_2(),)
            and
            (opt := self._tmp_3(),)
        ):
            return [literal, expr, literal_1, block, _loop0_2, opt];
        self._reset(mark)
        return None;

    @memoize
    def block(self) -> Optional[Any]:
        # block: INDENT statements DEDENT
        mark = self._mark()
        if (
            (_indent := self.expect('INDENT'))
            and
            (statements := self.statements())
            and
            (_dedent := self.expect('DEDENT'))
        ):
            return [_indent, statements, _dedent];
        self._reset(mark)
        return None;

    @memoize
    def expr(self) -> Optional[Any]:
        # expr: atom trailer*
        mark = self._mark()
        if (
            (atom := self.atom())
            and
            (_loop0_4 := self._loop0_4(),)
        ):
            return [atom, _loop0_4];
        self._reset(mark)
        return None;

    @memoize
    def trailer(self) -> Optional[Any]:
        # trailer: '(' expr? ')' | '.' NAME | OP atom
        mark = self._mark()
        if (
            (literal := self.expect('('))
            and
            (opt := self.expr(),)
            and
            (literal_1 := self.expect(')'))
        ):
            return [literal, opt, literal_1];
        self._reset(mark)
        if (
            (literal := self.expect('.'))
            and
            (name := self.name())
        ):
            return [literal, name];
        self._reset(mark)
        if (
            (op := self.op())
            and
            (atom := self.atom())
        ):
            return [op, atom];
        self._reset(mark)
        return None;

    @memoize
    def factor(self) -> Optional[Any]:
        # factor: atom
        mark = self._mark()
        if (
            (atom := self.atom())
        ):
            return atom;
        self._reset(mark)
        return None;

    @memoize
    def atom(self) -> Optional[Any]:
        # atom: NAME | NUMBER | STRING | '(' expr ')'
        mark = self._mark()
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        if (
            (number := self.number())
        ):
            return number;
        self._reset(mark)
        if (
            (string := self.string())
        ):
            return string;
        self._reset(mark)
        if (
            (literal := self.expect('('))
            and
            (expr := self.expr())
            and
            (literal_1 := self.expect(')'))
        ):
            return [literal, expr, literal_1];
        self._reset(mark)
        return None;

    @memoize
    def _loop1_1(self) -> Optional[Any]:
        # _loop1_1: statement
        mark = self._mark()
        children = []
        while (
            (statement := self.statement())
        ):
            children.append(statement)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_2(self) -> Optional[Any]:
        # _loop0_2: ('elif' expr ':' block)
        mark = self._mark()
        children = []
        while (
            (_tmp_5 := self._tmp_5())
        ):
            children.append(_tmp_5)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_3(self) -> Optional[Any]:
        # _tmp_3: 'else' ':' block
        mark = self._mark()
        if (
            (literal := self.expect('else'))
            and
            (literal_1 := self.expect(':'))
            and
            (block := self.block())
        ):
            return [literal, literal_1, block];
        self._reset(mark)
        return None;

    @memoize
    def _loop0_4(self) -> Optional[Any]:
        # _loop0_4: trailer
        mark = self._mark()
        children = []
        while (
            (trailer := self.trailer())
        ):
            children.append(trailer)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_5(self) -> Optional[Any]:
        # _tmp_5: 'elif' expr ':' block
        mark = self._mark()
        if (
            (literal := self.expect('elif'))
            and
            (expr := self.expr())
            and
            (literal_1 := self.expect(':'))
            and
            (block := self.block())
        ):
            return [literal, expr, literal_1, block];
        self._reset(mark)
        return None;

    KEYWORDS = ('def', 'elif', 'else', 'if')
    SOFT_KEYWORDS = ()


if __name__ == '__main__':
    from pegen.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
